<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    ':name was successfully created.' => ':name nou a fost cu succes creat',
    ':name was successfully updated.' => ':name a fost cu succes înnoit',
    'Album Images' => 'Imaginele albumului',
    'Create AlbumImage' => 'A crea album cu imagini',
    'DToggleAction::attributes is empty' => 'DToggleAction::atributele sunt goale',
    'Howdy' => 'Salut',
    'Manage Album Image' => 'Setările albumului',
    'Missing attribute {attribute}' => 'Atribulul lipsit {attribute}',
    'Password of user :name was changed successfully.' => 'Parola :name a fost schimbat cu succes',
    'Pictures' => 'Imagini',
    'Реестр недвижимости' => 'Registru de imobiliare',
    'Сотрудники' => 'Personal',
    'Ad creation type'=>'Ad creation type',
    'Содержание на английском' => 'Conținutul în limba engleză',
    'Содержание на молдавском' => 'Conținutul în limba moldovenească',
    'Содержание на русском' => 'Conținutul în limba rusă',
    'Тип содержания' => 'Tipul de conținut',
    'Название' => 'Numele',
    'Изображение' => 'Imagine',
    'Подзаголовок на английском' => 'Subtitlu în limba engleză',
    'Подзаголовок на молдавском' => 'Subtitlu în limba moldovenească',
    'Подзаголовок на русском' => 'Subtitlu în limba rusă',

);
