<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    '1-10 га' => '',
    '100-200 кв.м' => '',
    '15-25 000 EUR' => '',
    '200 кв.м - 1 га' => '',
    '25-50 000 EUR' => '',
    '50-100 000 EUR' => '',
    '50-100 кв.м' => '',
    '{n} комната|{n} комнаты|{n} комнат' => '',
    'Адрес' => '',
    'Белый' => '',
    'Город' => '',
    'Дом на земле' => '',
    'Дома на земле' => '',
    'Евро' => '',
    'Единицы измерения площади земельного участка' => '',
    'Единицы измерения площади помещений' => '',
    'Земельный участок' => '',
    'Земельные участки' => '',
    'кв.м' => '',
    'Квартира' => '',
    'Квартиры' => '',
    'Количество комнат' => '',
    'Количество этажей дома' => '',
    'Коммерческие площади' => '',
    'Новострой' => '',
    'Общая площадь помещений' => '',
    'Объекты недвижимости' => '',
    'Описание' => '',
    'Офис' => '',
    'Площадь' => '',
    'Площадь жилых помещений' => '',
    'Площадь земельного участка' => '',
    'Провинция' => '',
    'Производственные площади' => '',
    'Район' => '',
    'Серый' => '',
    'Складские площади' => '',
    'Состояние помещений' => '',
    'Вторичка' => '',
    'Статус' => '',
    'Страна' => '',
    'Тип недвижимости' => '',
    'Улица' => '',
    'Этаж, где расположена квартира' => '',
    'Является ли объект недвижимости новостроем' => '',
    'больше 100 000 EUR' => '',
    'больше 10га' => '',
    'га.' => '',
    'до 15 000 EUR' => '',
    'до 50 кв.м' => '',
    'кв.м' => '',
    'м.' => '',
    'а.' => '',
    'га.' => '',
    'этаж' => '',
    '<h2>Спасибо!</h2> <p>Мы свяжемся с Вами в ближайшее время!</p>' => '',
);
