<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'ADD' => '',
    'E-mail is not valid!' => '',
    'Email' => '',
    'Error, no POST data' => '',
    'Error, token should be sent' => '',
    'Invalid request. Please do not repeat this request again.' => '',
    'Name' => '',
    'No results' => '',
    'No such record' => '',
    'Not json data' => '',
    'Notify' => '',
    'POST is empty' => '',
    'Password' => '',
    'Repeat password' => '',
    'Surname' => '',
    'Token wrong' => '',
    '{sitename} [br] Лучшие среди профессионалов' => '{sitename} [br] We\'re always do our best',
    'НАШИ КОНТАКТЫ' => 'OUR CONTACTS',
    'Ad creation type'=>'Ad creation type',
    'Russian'=>'Russian',
    'Moldavian'=>'Moldavian',
    'English'=>'English',
    'Нет'=>'No',
    'Да'=>'Yes',
);
