<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Валюта' => 'Valută',
    'Все' => 'Toate',
    'Детали' => 'Detalii',
    'Доллары США' => 'Dolarii SUA',
    'Евро' => 'Euro',
    'Заголовок на английском' => 'Titlu în limba engleză',
    'Заголовок на молдавском' => 'Titlu în limba moldovenească',
    'Заголовок на русском' => 'Titlu în limba rusă',
    'Молдавский лей' => 'Leu moldovenesc',
    'Нравится' => 'Place',
    'Объявления' => 'Anunțuri',
    'Описание на английском' => 'Descripție în engleză',
    'Описание на молдавском' => 'Descripție în moldovenească',
    'Описание на русском' => 'Descripție în rusă',
    'Продажа' => 'Vânzare',
    'Аренда' => 'Oferte de chirie',
    'Тип объявления' => 'Tipul anunțului',
    'Убрать' => 'Șterge',
    'Цена' => 'Preț',
    'Молдова - Кишинёв' => 'Moldova - Chișinau',
    'ПЛОЩАДЬ - ВСЁ' => 'SQUARE - Toate',
    'ЦЕНА - ВСЁ' => 'PREȚ - Toate',
    'нравится' => 'place',
    'детали' => 'detalii',
    'Разместить на главной странице' => 'Plasați pe pagina principală',
    'Особенности' => 'Caracteristici',
    'Выберите особенности объекта' => 'Selectați caracteristicile obiectului',
);
