<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'ADD' => 'ADĂUGA',
    'E-mail is not valid!' => 'E-mail nu este validă!',
    'Email' => 'Email',
    'Error, no POST data' => 'Eroare, datele nu au fost postate',
    'Error, token should be sent' => 'Eroare, trebuie să primiți un mesaj',
    'Invalid request. Please do not repeat this request again.' => 'Solicitare este incorectă. Vă rog să nu o introduceți repetat',
    'Name' => 'PreNume',
    'No results' => 'Fără rezultate',
    'No such record' => 'Nu există un astfel de înregistrare',
    'Not json data' => 'Nu sunt datele json',
    'Notify' => 'Notifica',
    'POST is empty' => 'POST este gol',
    'Password' => 'Parolă',
    'Repeat password' => 'Repeta parola',
    'Surname' => 'Nume',
    'Token wrong' => 'Notificare greșită',
    '{sitename} [br] Лучшие среди профессионалов' => 'Cei mai buni între profesioniști',
    'НАШИ КОНТАКТЫ' => 'CONTACTE',
    'Ad creation type'=>'Ad creation type',
    'Russian'=>'Rusă',
    'Moldavian'=>'Moldovenească',
    'English'=>'Engleză',
    'Нет'=>'Nu',
    'Да'=>'Da',
);
