<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Валюта' => 'Сurrency',
    'Все' => 'All',
    'Детали' => 'Details',
    'Доллары США' => 'USD',
    'Евро' => 'EUR',
    'Заголовок на английском' => 'Title in English',
    'Заголовок на молдавском' => 'Title in Moldavian',
    'Заголовок на русском' => 'Title in Russian',
    'Земельный участок' => 'Landplot',
    'КОМНАТЫ - ВСЁ' => 'ROOMS - ALL',
    'Молдавский лей' => 'MDL',
    'Молдова - Кишинёв' => 'Moldova - Kishinev',
    'Нравится' => 'To shortlist',
    'Объявления' => 'Announcements',
    'Описание на английском' => 'Description in English',
    'Описание на молдавском' => 'Description in Moldavian',
    'Описание на русском' => 'Description in Russian',
    'ПЛОЩАДЬ - ВСЁ' => 'AREA - ALL',
    'Площадь' => 'AREA',
    'Предложение' => 'Offer',
    'Применить фильтры' => 'Apply filters',
    'Продажа' => 'For sale',
    'РАЙОНЫ КИШИНЁВА' => 'Kishinev neighboors',
    'Аренда' => 'For rent',
    'Тип недвижимости' => 'Property type',
    'Тип объявления' => 'Announcement type',
    'Убрать' => 'Remove',
    'ЦЕНА - ВСЁ' => 'PRICE - ALL',
    'Цена' => 'Price',
    'Что именно вы ищете?' => 'What are you looking for?',
    'назад' => 'back',
    'нравится' => 'like',
    'подробности' => 'details',
    'сбросить' => 'clear',
    'Разместить на главной странице' => 'Place on the main page',
    'Особенности' => 'Features',
    'Выберите особенности объекта' => 'Select object features',
);
