<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'ADD' => 'ДОБАВИТЬ',
    'E-mail is not valid!' => 'Неправильный E-mail',
    'Email' => 'Email',
    'Error, no POST data' => 'Ошибка, данные в POST отсутствуют',
    'Error, token should be sent' => 'Ошибка, необходио посылать токен',
    'Invalid request. Please do not repeat this request again.' => 'Неверный запрос. Пожалуйста, не отправляйте его снова',
    'Name' => 'Имя',
    'No results' => 'Результатов нет',
    'No such record' => 'Нет такой записи',
    'Not json data' => 'Данные не в формате json',
    'Notify' => 'Уведоление',
    'POST is empty' => 'Пустой POST',
    'Password' => 'Пароль',
    'Repeat password' => 'Повторите пароль',
    'Surname' => 'Фамилия',
    'Token wrong' => 'Неверный токен',
    '{sitename} [br] Лучшие среди профессионалов' => '',
    'НАШИ КОНТАКТЫ' => '',
    'Images' => 'Фотографии',
    'Ad creation type'=>'Способ создания объявлений',
    'Russian'=>'Русский',
    'Moldavian'=>'Молдавский',
    'English'=>'Английский',
);
