<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    ':name was successfully created.' => '',
    ':name was successfully updated.' => '',
    'Album Images' => '',
    'Create AlbumImage' => '',
    'DToggleAction::attributes is empty' => '',
    'Howdy' => '',
    'Manage Album Image' => '',
    'Missing attribute {attribute}' => '',
    'Password of user :name was changed successfully.' => '',
    'Pictures' => '',
    'Реестр недвижимости' => 'All property',
    'Сотрудники' => 'Staff',
    'Ad creation type' => 'Ad creation type',
    'Содержание на английском' => 'Content in English',
    'Содержание на молдавском' => 'Content in Moldavian',
    'Содержание на русском' => 'Content in Russian',
    'Тип содержания' => 'Type of content',
    'Название' => 'Name',
    'Изображение' => 'Image',
    'Подзаголовок на английском' => 'Subtitle in English',
    'Подзаголовок на молдавском' => 'Subtitle in Moldavian',
    'Подзаголовок на русском' => 'Subtitle in Russian',
);
